@baseUrl = http://localhost:8081/api

###get all todo
GET {{baseUrl}}/todo
content-type: application/json

### find by id todo
GET {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990
content-type: application/json

### create todo detail
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/create-detail
accept: */*
content-type: application/json

{
  "d_title": "d_title_created",
  "d_content": "d_content_created"
}

### update todo detail
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/update-detail
accept: */*
content-type: application/json

{
  "_id": "6331cb99cf3dd9dadec3b996",
  "d_title": "d_title_upadted_2",
  "d_content": "d_content__upadted"
}

### delete todo detail
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/delete-detail
accept: */*
content-type: application/json

{
  "_id": "633454aeb1c2072442a2fa90"
}
