@baseUrl = http://localhost:8081/api

###get all todo
GET {{baseUrl}}/todo
content-type: application/json

### find by id todo
GET {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990
content-type: application/json

### create todo task
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/create-task
accept: */*
content-type: application/json

{
  "t_content": "t_content_create2",
  "t_status": 0,
  "t_order_number": 2
}

### update-status-to-conpleted-task
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/update-status-to-conpleted-task
accept: */*
content-type: application/json

{
  "_id": "633589cb29bf4eeb6f0c1548",
  "t_status": 1,
  "t_left": 0,
  "t_right": 0,
}

### update todo task
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/update-task
accept: */*
content-type: application/json

{
  "_id": "63357d4fb24395f0dd0892fb",
  "d_title": "d_title_upadted_2",
  "d_content": "d_content__upadted"
}

### delete todo task
PUT {{baseUrl}}/todo/6331cb6ecf3dd9dadec3b990/delete-task
accept: */*
content-type: application/json

{
  "_id": "633ba10fd98b9ffb950b26b9"
}